let carsMakeData = [
  {
    label: "Popular Brands",
    options: ["BMW", "Mercedes", "Audi", "Volkswagen", "Tesla", "Toyota", "Honda", "Ford"],
  },
  {
    label: "Other Brands",
    options: ["Hyundai", "Kia", "Mazda", "Nissan", "Subaru", "Volvo", "Porsche", "Range Rover", "Jaguar", "Lexus", "Chevrolet", "SEAT", "Opel"],
  },
];

let motorcycleMakeData = [
  { label: "Make", options: ["Yamaha", "Suzuki", "Honda"] },
  { label: "Other", options: ["BMW", "KTM", "CFMoto"] },
];

let prices = [
  {
    label: "Price up to (€)",
    options: [
      "€250",
      "€500",
      "€1000",
      "€1500",
      "€2000",
      "€2500",
      "€3000",
      "€4000",
      "€5000",
      "€6000",
      "€7000",
      "€8000",
      "€9000",
      "€10000",
      "€12500",
      "€15000",
      "€17500",
      "€20000",
      "€30000",
      "€40000",
      "€50000",
      "€75000",
      "€100000",
      "€200000",
      "€300000",
      "€400000",
      "€500000",
    ],
  },
];

let firstRegistration = [
  {
    label: "First registration from",
    options: [
      "2024",
      "2023",
      "2022",
      "2021",
      "2020",
      "2019",
      "2018",
      "2017",
      "2016",
      "2015",
      "2014",
      "2013",
      "2012",
      "2011",
      "2010",
      "2009",
      "2008",
      "2007",
      "2006",
      "2005",
      "2004",
      "2003",
      "2002",
      "2001",
      "2000",
      "1999",
      "1998",
      "1997",
      "1996",
      "1995",
      "1994",
      "1993",
      "1992",
      "1991",
      "1990",
      "1989",
      "1988",
      "1987",
      "1986",
      "1985",
      "1984",
      "1983",
      "1982",
      "1981",
      "1980",
      "1979",
      "1978",
      "1977",
      "1976",
      "1975",
      "1974",
      "1973",
      "1972",
      "1971",
      "1970",
      "1969",
      "1968",
      "1967",
      "1966",
      "1965",
      "1964",
      "1963",
      "1962",
      "1961",
      "1960",
      "1959",
      "1958",
      "1957",
      "1956",
      "1955",
      "1954",
      "1953",
      "1952",
      "1951",
      "1950",
    ],
  },
];

let countries = [{ label: "Europe", options: ["Germany", "Italy", "France"] }];

let fuelTypes = [{ label: "Fuel Type", options: ["Petrol", "Diesel", "Electric", "Hybrid"] }];

let mileageOptions = [
  {
    label: "Mileage",
    options: [
      "5,000",
      "10,000",
      "20,000",
      "30,000",
      "40,000",
      "50,000",
      "75,000",
      "100,000",
      "125,000",
      "150,000",
      "200,000",
      "300,000",
      "400,000",
      "500,000",
      "600,000",
      "700,000",
      "800,000",
      "900,000",
      "1,000,000",
    ],
  },
];

let horsepowerOptions = [{ label: "Horsepower", options: ["50", "75", "100", "125", "150", "200", "250", "300", "400", "500", "600", "700", "800", "900", "1000"] }];

let carsModelData = {
  BMW: {
    label: "Model",
    options: [
      "320i",
      "320d",
      "325i",
      "330i",
      "330d",
      "335i",
      "340i",
      "340d",
      "520i",
      "520d",
      "525i",
      "525d",
      "530i",
      "530d",
      "535i",
      "540i",
      "540d",
      "730i",
      "730d",
      "740i",
      "740d",
      "750i",
      "760i",
      "760d",
      "X1",
      "X1 xDrive",
      "X3",
      "X3 M",
      "X3 xDrive",
      "X5",
      "X5 M",
      "X5 xDrive",
      "X7",
      "X7 xDrive",
      "Z4",
      "Z4 M",
      "i4",
      "i7",
      "M2",
      "M3",
      "M4",
      "M5",
      "M6",
      "M8",
    ],
  },
  Mercedes: {
    label: "Model",
    options: [
      "A150",
      "A160",
      "A170",
      "A180",
      "A200",
      "A250",
      "C180",
      "C200",
      "C220",
      "C250",
      "C300",
      "C43",
      "C63",
      "C63 AMG",
      "E200",
      "E220",
      "E250",
      "E300",
      "E350",
      "E43",
      "E53",
      "E63",
      "E63 AMG",
      "S280",
      "S300",
      "S320",
      "S350",
      "S400",
      "S450",
      "S500",
      "S580",
      "S63",
      "S63 AMG",
      "S65",
      "S65 AMG",
      "G250",
      "G350",
      "G400",
      "G500",
      "G63",
      "GLA200",
      "GLA250",
      "GLA35",
      "GLA45",
      "GLC200",
      "GLC220",
      "GLC250",
      "GLC300",
      "GLC43",
      "GLC63",
      "GLE200",
      "GLE220",
      "GLE250",
      "GLE300",
      "GLE350",
      "GLE450",
      "GLE53",
      "GLE63",
      "GLS400",
      "GLS450",
      "GLS500",
      "GLS580",
      "GLS63",
      "EQC",
      "EQE",
      "EQS",
    ],
  },
  Audi: {
    label: "Model",
    options: [
      "A1",
      "A1 Sportback",
      "A3",
      "A3 Sportback",
      "A3 Sedan",
      "A4",
      "A4 Allroad",
      "A4 Avant",
      "A5",
      "A5 Coupe",
      "A5 Cabriolet",
      "A5 Sportback",
      "A6",
      "A6 Allroad",
      "A6 Avant",
      "A6 Sedan",
      "A8",
      "A8 L",
      "Q2",
      "Q2 L",
      "Q3",
      "Q3 Sportback",
      "Q4 e-tron",
      "Q4 Sportback e-tron",
      "Q5",
      "Q5 Sportback",
      "Q7",
      "Q7 Sportback",
      "Q8",
      "Q8 e-tron",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "TT",
      "TT Coupe",
      "TT Roadster",
    ],
  },
  Volkswagen: {
    label: "Model",
    options: [
      "Golf",
      "Golf GTI",
      "Golf R",
      "Golf Alltrack",
      "Polo",
      "Polo GTI",
      "Passat",
      "Passat Alltrack",
      "Passat Estate",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "T-Roc",
      "T-Roc Cabriolet",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.Buzz",
      "Jetta",
      "Jetta GLI",
      "Arteon",
      "Arteon Shooting Brake",
      "Beetle",
      "Beetle Cabriolet",
      "Caddy",
      "Transporter",
    ],
  },
  Tesla: {
    label: "Model",
    options: ["Model 3", "Model 3 Performance", "Model S", "Model S Plaid", "Model X", "Model Y", "Roadster", "Cybertruck"],
  },
  Toyota: {
    label: "Model",
    options: [
      "Corolla",
      "Corolla Hatchback",
      "Corolla Cross",
      "Camry",
      "RAV4",
      "RAV4 Prime",
      "Highlander",
      "4Runner",
      "Tacoma",
      "Tundra",
      "Prius",
      "Prius Prime",
      "C-HR",
      "bZ4X",
      "Venza",
      "GR Supra",
      "Yaris",
      "Yaris Cross",
      "Land Cruiser",
    ],
  },
  Honda: {
    label: "Model",
    options: ["Civic", "Civic Si", "Civic Type R", "Accord", "CR-V", "Pilot", "Odyssey", "Fit", "Ridgeline", "HR-V", "Insight", "Clarity", "Passport"],
  },
  Ford: {
    label: "Model",
    options: [
      "Mustang",
      "Mustang Mach-E",
      "Mustang EcoBoost",
      "Focus",
      "Focus ST",
      "Focus RS",
      "Fiesta",
      "Fiesta ST",
      "Fusion",
      "F-150",
      "F-150 Raptor",
      "F-150 Lightning",
      "Ranger",
      "Ranger Raptor",
      "Escape",
      "Escape Hybrid",
      "Explorer",
      "Edge",
      "Bronco",
      "Bronco Sport",
    ],
  },
  Hyundai: {
    label: "Model",
    options: [
      "i20",
      "i20 N",
      "i30",
      "i30 N",
      "i30 Fastback",
      "Elantra",
      "Sonata",
      "Santa Fe",
      "Tucson",
      "Tucson N",
      "Kona",
      "Kona N",
      "Kona Electric",
      "Venue",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
      "Nexo",
      "Palisade",
    ],
  },
  Kia: {
    label: "Model",
    options: ["Picanto", "Rio", "Cerato", "Cerato GT", "Stinger", "Sportage", "Sorento", "Telluride", "Niro", "Niro EV", "Niro Hybrid", "EV6", "Seltos"],
  },
  Mazda: {
    label: "Model",
    options: ["Mazda 2", "Mazda 2 Sport", "Mazda 3", "Mazda 3 Turbo", "Mazda 6", "Mazda 6 Turbo", "CX-3", "CX-5", "CX-9", "MX-5", "MX-5 Miata", "MX-30"],
  },
  Nissan: {
    label: "Model",
    options: ["Micra", "Altima", "Maxima", "Qashqai", "Qashqai e-Power", "Rogue", "Rogue Sport", "Murano", "Pathfinder", "GT-R", "Leaf", "Leaf Plus", "Ariya"],
  },
  Subaru: {
    label: "Model",
    options: [
      "Impreza",
      "Impreza Sport",
      "Crosstrek",
      "Crosstrek Hybrid",
      "Outback",
      "Forester",
      "Forester Wilderness",
      "Ascent",
      "BRZ",
      "WRX",
      "WRX STI",
      "Legacy",
      "Legacy Touring",
    ],
  },
  Volvo: {
    label: "Model",
    options: [
      "V40",
      "S60",
      "S60 Polestar",
      "S90",
      "V60",
      "V60 Cross Country",
      "V90",
      "V90 Cross Country",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC60 Recharge",
      "XC90",
      "XC90 Recharge",
    ],
  },
  Porsche: {
    label: "Model",
    options: [
      "911",
      "911 Carrera",
      "911 Turbo",
      "911 S",
      "911 GTS",
      "911 Cabriolet",
      "911 Targa",
      "Cayenne",
      "Cayenne Coupe",
      "Cayenne E-Hybrid",
      "Macan",
      "Macan Electric",
      "Panamera",
      "Panamera Turbo",
      "Panamera Sport Turismo",
      "Taycan",
      "Boxster",
      "Boxster GTS",
    ],
  },
  "Range Rover": {
    label: "Model",
    options: ["Range Rover", "Range Rover Sport", "Range Rover Sport SVR", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender"],
  },
  Jaguar: {
    label: "Model",
    options: ["XE", "XE SVO", "XF", "XF SVO", "F-PACE", "F-TYPE", "E-PACE", "I-PACE"],
  },
  Lexus: {
    label: "Model",
    options: [
      "IS",
      "IS F",
      "ES",
      "LS",
      "LS Hybrid",
      "UX",
      "UX Hybrid",
      "UX Electric",
      "NX",
      "NX 350h",
      "RX",
      "RX L",
      "RX 450h+",
      "LX",
      "LX 600",
      "RC",
      "RC F",
      "LC",
      "LC Convertible",
      "RZ",
    ],
  },
  Chevrolet: {
    label: "Model",
    options: [
      "Spark",
      "Malibu",
      "Impala",
      "Equinox",
      "Equinox EV",
      "Blazer",
      "Blazer EV",
      "Tahoe",
      "Tahoe RST",
      "Traverse",
      "Bolt",
      "Bolt EUV",
      "Corvette",
      "Corvette Z06",
      "Silverado",
      "Silverado EV",
    ],
  },
  SEAT: { label: "Model", options: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"] },
  Opel: { label: "Model", options: ["Corsa", "Astra", "Insignia", "Grandland", "Mokka", "Combo"] },
};

let motorcycleModelData = {
  Yamaha: { label: "Model", options: ["YZF-R125", "YZF-R6", "YZF-R7", "YZF-R1", "YZF-R1M", "MT-07", "MT-09"] },
  Suzuki: { label: "Model", options: ["GSX-250R", "GSX-R600", "GSX-R750", "GSX-R1000", "GSX-R1000R", "Hayabusa"] },
  Honda: { label: "Model", options: ["CBR-125R", "CBR-300R", "CBR-500R", "CBR-650R", "CBR-600RR", "CBR-1000RR"] },
};

let bodyTypes = [{ label: "Body Type", options: ["Sedan", "SUV", "Coupe", "Hatchback", "Wagon", "Convertible", "Van", "Pickup"] }];

let transmissions = [{ label: "Transmission", options: ["Manual", "Automatic", "Semi-automatic"] }];

let driveTypes = [{ label: "Drive Type", options: ["FWD", "RWD", "AWD", "4x4"] }];

let colors = [{ label: "Color", options: ["Black", "White", "Silver", "Gray", "Blue", "Red", "Green", "Brown", "Beige", "Yellow", "Orange"] }];

let sellerTypes = [{ label: "Seller Type", options: ["Private", "Dealer"] }];

export {
  carsMakeData,
  carsModelData,
  countries,
  firstRegistration,
  motorcycleMakeData,
  motorcycleModelData,
  prices,
  fuelTypes,
  bodyTypes,
  transmissions,
  driveTypes,
  colors,
  sellerTypes,
  mileageOptions,
  horsepowerOptions,
};
