export const vehicleBrandsData = {
  BMW: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "X7", "M340i", "M440i", "Z4", "i4", "i7", "M2", "M3", "M4", "M5"],
  Mercedes: [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
    "AMG A 45",
    "AMG C 63",
    "AMG E 63",
    "AMG GT",
    "EQC",
    "EQE",
    "EQS",
    "SL",
  ],
  Audi: ["A1", "A3", "A4", "A6", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "RS3", "RS4", "RS5", "TT", "e-tron GT"],
  Volkswagen: ["Golf", "Polo", "Passat", "Tiguan", "Touareg", "T-Roc", "ID.3", "ID.4", "ID.5", "Jetta", "Arteon", "Beetle", "Caddy", "Transporter"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y", "Roadster", "Cybertruck"],
  Toyota: ["Corolla", "Camry", "RAV4", "Highlander", "4Runner", "Tacoma", "Tundra", "Prius", "C-HR", "Venza", "GR Supra", "Yaris", "Land Cruiser"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "Fit", "Ridgeline", "HR-V", "Insight", "Clarity", "Passport"],
  Ford: ["Mustang", "Focus", "Fiesta", "Fusion", "F-150", "Ranger", "Escape", "Explorer", "Edge", "Bronco", "Mustang Mach-E"],
  Hyundai: ["i20", "i30", "Elantra", "Sonata", "Santa Fe", "Tucson", "Kona", "Venue", "Ioniq", "Nexo", "Palisade"],
  Kia: ["Picanto", "Rio", "Cerato", "Stinger", "Sportage", "Sorento", "Telluride", "Niro", "EV6", "Seltos"],
  Mazda: ["Mazda 2", "Mazda 3", "Mazda 6", "CX-3", "CX-5", "CX-9", "MX-5", "MX-30"],
  Nissan: ["Micra", "Altima", "Maxima", "Qashqai", "Rogue", "Murano", "Pathfinder", "GT-R", "Leaf", "Ariya"],
  Subaru: ["Impreza", "Crosstrek", "Outback", "Forester", "Ascent", "BRZ", "WRX", "Legacy"],
  Volvo: ["V40", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40 Recharge"],
  Porsche: ["911", "911 Turbo", "911 Carrera", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster"],
  "Range Rover": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport"],
  Jaguar: ["XE", "XF", "F-PACE", "F-TYPE", "E-PACE", "I-PACE"],
  Lexus: ["IS", "ES", "LS", "UX", "NX", "RX", "LX", "RC", "LC", "RZ"],
  Chevrolet: ["Spark", "Malibu", "Impala", "Equinox", "Blazer", "Tahoe", "Traverse", "Bolt", "Corvette", "Silverado"],
};
