# Generated by Django 5.2.8 on 2025-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
