# Generated by Django 5.2.8 on 2026-03-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('van', 'Van'), ('pickup', 'Pickup')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'FWD'), ('rwd', 'RWD'), ('awd', 'AWD'), ('4x4', '4x4')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine_displacement',
            field=models.IntegerField(blank=True, help_text='In cc', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='exterior_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('brown', 'Brown'), ('beige', 'Beige'), ('yellow', 'Yellow'), ('orange', 'Orange')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='interior_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('brown', 'Brown'), ('beige', 'Beige'), ('yellow', 'Yellow'), ('orange', 'Orange')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_doors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='previous_owners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('dealer', 'Dealer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi-automatic', 'Semi-automatic')], max_length=20, null=True),
        ),
    ]
