# Generated by Django 5.2.8 on 2026-03-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dealer_request_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_type',
            field=models.CharField(choices=[('private', 'Private'), ('dealer', 'Dealer')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='DealerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_addresses', to='listings.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DealerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('number', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_phones', to='listings.userprofile')),
            ],
        ),
    ]
